# vim: ft=dosini
[Metadata]
Name=Nord-Dark
Version=0.1
Author=tonyfettes
Description=Nord Color Theme (Dark)
ScaleWithDPI=True

[InputPanel]
# 字体
Font=Noto Sans CJK SC 13
# 非选中候选字颜色
NormalColor=#d8dee9
# 选中候选字颜色
HighlightCandidateColor=#eceff4
# 高亮前景颜色(输入字符颜色)
HighlightColor=#eceff4
# 输入字符背景颜色
HighlightBackgroundColor=#5e81ac
# 
Spacing=5

[InputPanel/TextMargin]
# 候选字对左边距
Left=12
# 候选字对右边距
Right=12
# 候选字向上边距
Top=7
# 候选字向下边距
Bottom=7

[InputPanel/Background]
Color=#3b4252

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#5e81ac

[InputPanel/Highlight/Margin]
# 高亮区域左边距
Left=12
# 高亮区域右边距
Right=12
# 高亮区域上边距
Top=8
# 高亮区域下边距
Bottom=8

[Menu]
Font=Noto Sans CJK SC 11
NormalColor=#e5e9f0
#HighlightColor=#4c566a
Spacing=4

[Menu/Background]
Color=#3b4252

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#4c566a

[Menu/Highlight/Margin]
Left=12
Right=12
Top=5
Bottom=5

[Menu/Separator]
Color=#2e3440

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
